Models/Dean.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace CapSystemFinal.Models
{
    public class Dean
    {
        [Key]
        public int DeanId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string UserId { get; set; } // FK to IdentityUser.Id

        [ForeignKey("UserId")]
        public IdentityUser User { get; set; }

        // Optional: link to complaints
        public ICollection<Complaint> Complaints { get; set; }
    }

}

Controllers/DeansController.cs
using System.Security.Claims;
using CapSystemFinal.Data;
using CapSystemFinal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CapSystemFinal.Controllers
{

    [Authorize(Roles = SD.Role_Dean)]
    public class DeansController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public DeansController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        //public IActionResult Index()
        //{
        //    return View();
        //}


        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);




            //var dean = await _context.Deans.FirstOrDefaultAsync(d => d.UserId == userId);

            //Dean dean = new Dean
            //{
            //    Name = "Dean John Smith",
            //    UserId = userId // <-- this links the Dean to the IdentityUser
            //};

            //_context.Deans.Add(dean);
            //await _context.SaveChangesAsync();

            var dean = await _context.Deans.FirstOrDefaultAsync(d => d.UserId == userId);

            if (dean == null)
            {
                // Return a custom view or message
                return Content("Dean profile not found for this user.");
            }
            ViewBag.DeanName = dean.Name;

            //var complaints = await _context.Complaints
            //    .Include(c => c.Dean)
            //    .Where(c => c.DeanId == dean.DeanId)
            //    .ToListAsync();
            var complaints = await _context.Complaints
                .Include(c => c.complaintStatus)
    .Include(c => c.transformationDirection)
    .Include(c => c.complaintType)
    .Where(c => c.DeanId == dean.DeanId)
    .ToListAsync();
            return View(complaints);

        }






        // GET: Complaints/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaintFromDb = _context.Complaints.FirstOrDefault(u => u.ComplaintId == id);
            if (complaintFromDb == null)
            {
                return NotFound();
            }
            //ViewData["CurrentDate"] = new SelectList(_context.Set<Complaint>(), "id", "id", complaint.date);
            ViewData["UserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            ViewData["CompTypeId"] = new SelectList(_context.ComplaintType, "Id", "Description");
            ViewData["ComplaintStatusId"] = new SelectList(_context.ComplaintStatus, "Id", "status");
            ViewData["TransformationDirectionId"] = new SelectList(_context.TransformationDirection, "Id", "Description");



            return View(complaintFromDb);
        }

        // POST: Complaints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Complaint obj)
        {

            var userId = _userManager.GetUserId(User);

            //var dean = await _context.Deans.FirstOrDefaultAsync(d => d.UserId == userId);

            //if (dean == null)
            //{
            //    // Return a custom view or message
            //    return Content("Dean profile not found for this user.");
            //}


            if (ModelState.IsValid)
            {
                // 1. Get the existing complaint from database
                var complaintFromDb = _context.Complaints.Find(obj.ComplaintId);

                if (complaintFromDb == null)
                {
                    return NotFound();
                }


               
                complaintFromDb.subject = obj.subject;
                complaintFromDb.description = obj.description;
                complaintFromDb.ComplaintStatusId = obj.ComplaintStatusId;
                complaintFromDb.CompTypeId = obj.CompTypeId;
                complaintFromDb.TransformationDirectionId = obj.TransformationDirectionId;



              

                // 🧠 Logic to get Dean by selected TransformationDirection
                var selectedDirection = await _context.TransformationDirection
                    .FirstOrDefaultAsync(td => td.Id == complaintFromDb.TransformationDirectionId);

                if (selectedDirection != null)
                {
                    // Match by description (assuming Dean.Name == Direction.Description)
                    var dean = await _context.Deans
                        .FirstOrDefaultAsync(d => d.Name == selectedDirection.Description);

                    if (dean != null)
                    {
                        complaintFromDb.DeanId = dean.DeanId;
                    }

                }



                // 3. Explicitly mark as modified (optional but good practice)
                _context.Entry(complaintFromDb).State = EntityState.Modified;

                _context.SaveChanges();



                return RedirectToAction("Index");
                //  try
                // {
                //_context.Attach(complaint);
                //_context.Entry(complaint).State = EntityState.Modified;
                //_context.Update(obj);
                //_context.SaveChangesAsync();
                //_context.SaveChanges();

                //}
                //catch (DbUpdateConcurrencyException)
                //{
                //    if (!ComplaintExists(complaint.ComplaintId))
                //    {
                //        return NotFound();
                //    }
                //    else
                //    {
                //        throw;
                //    }
                //}
                //return RedirectToAction("Index");
            }
            ViewData["ComplaintStatusId"] = new SelectList(_context.Set<ComplaintStatus>(), "id", "id", obj.ComplaintStatusId);
            ViewData["CompTypeId"] = new SelectList(_context.Set<ComplaintType>(), "Id", "Id", obj.CompTypeId);
            ViewData["TransformationDirectionId"] = new SelectList(_context.Set<TransformationDirection>(), "Id", "Id", obj.TransformationDirectionId);
            return View(obj);
        }



        // GET: Complaints/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaint = await _context.Complaints
                .Include(c => c.complaintStatus)
                .Include(c => c.complaintType)
                .Include(c => c.transformationDirection)
                .FirstOrDefaultAsync(m => m.ComplaintId == id);
            if (complaint == null)
            {
                return NotFound();
            }

            ViewData["UserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            ViewData["CompTypeId"] = _context.ComplaintType.Find(complaint.CompTypeId)?.Description;
            ViewData["ComplaintStatusId"] = _context.ComplaintStatus.Find(complaint.ComplaintStatusId)?.status;
            //ViewData["TransformationDirectionId"] = new SelectList(_context.TransformationDirection, "Id", "Description");
            ViewData["TransformationDirectionId"] = _context.TransformationDirection.Find(complaint.TransformationDirectionId)?.Description;
            return View(complaint);
        }

        // POST: Complaints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var complaint = await _context.Complaints.FindAsync(id);
            if (complaint != null)
            {
                _context.Complaints.Remove(complaint);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



    }
}

Views/Deans/Delete.cshtml
@model CapSystemFinal.Models.Complaint

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Complaint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.complaintStatus)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.ComplaintStatusId
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.complaintType)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.CompTypeId
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.transformationDirection)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.TransformationDirectionId
        </dd>
    </dl>
    
    <form asp-controller="Deans" asp-action="Delete">
        <input type="hidden" asp-for="ComplaintId" />
        <button type="submit" value="Delete" class="btn btn-danger"><i class="bi bi-archive-fill"></i> Delete</button>
        @* <a asp-action="Index">Back to List</a> *@
        <a asp-controller="Deans" asp-action="Index" class="btn btn-outline">
            <i class="fas fa-arrow-left"></i>
            Back
        </a>
    </form>
</div>

Views/Deans/Edit.cshtml
@using System.Security.Claims

@model CapSystemFinal.Models.Complaint

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Complaint</h4>

<hr />
<div class="row">   
    <div class="col-md-12">
        <form  method="post">
            <!-- Add this hidden field -->
            <input type="hidden" asp-for="ComplaintId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="subject" class="control-label"></label>
                <input asp-for="subject" class="form-control" />
                <span asp-validation-for="subject" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control pb-5" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="date" class="control-label"></label>
                <input type="date" asp-for="date" class="form-control" readonly />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="ComplaintStatusId" class="control-label"></label>
                <select asp-for="ComplaintStatusId" class="form-control" asp-items="ViewBag.ComplaintStatusId">
                    <option asp-for="ComplaintStatusId">--Select Status --</option>

                </select>
                <span asp-validation-for="ComplaintStatusId" class="text-danger"></span>
            </div>
            
            <div class="form-group mb-3">
                <label hidden asp-for="UserId" class="control-label"></label>
                <input type="hidden" name="userId" asp-for="UserId" class="form-control" value="@ViewData["UserId"]" />
            </div>
            <div class="form-group mb-3">
                <label asp-for="CompTypeId" class="control-label"></label>
                <select asp-for="CompTypeId" class="form-control" asp-items="ViewBag.CompTypeId"></select>
                <span asp-validation-for="CompTypeId" class="text-danger"></span>
            </div>
            <div class="form-group  mb-4">
                <label asp-for="TransformationDirectionId" class="control-label"></label>
                <select asp-for="TransformationDirectionId" class="form-control" asp-items="ViewBag.TransformationDirectionId"></select>
                <span asp-validation-for="TransformationDirectionId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 d-flex gap-3">
                @* <input type="submit" value="Create"  class="btn btn-primary" /> *@
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-pencil-square"></i>
                    Edit
                </button>
                <a asp-action="Index" class="btn btn-outline">
                    <i class="fas fa-arrow-left"></i>
                    Back
                </a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Deans/Index.cshtml
@model IEnumerable<CapSystemFinal.Models.Complaint>

@{
    ViewData["Title"] = "Dean Complaints";
}

<link rel="stylesheet" href="~/css/Student/index.css" />


<h1 class="m-3">Complaints Assigned to You</h1>
<hr />

<h2 class="m-3">Welcome, Dr. @ViewBag.DeanName</h2>



<div class="d-flex">
    <div class="search-container m-4  w-100 position-relative">

        <input type="text" id="search-input" placeholder="Search Complaints..." class="ps-4 p-2 rounded-2 border-0 w-100" />
        <i class="bi bi-search position-absolute position-adjust text-danger "></i>

    </div>






    <div class="filter-group m-4 w-50 align-content-center">
        <label id="status-filter-label"></label>
        <select id="status-filter" class="w-75 p-2 rounded-2 border-0 ">
            <option value="">Status</option>
            <option value="Pending">Pending</option>
            <option value="In Progress">In Progress</option>
            <option value="Resolved">Resolved</option>
            <option value="Closed">Closed</option>
        </select>



    </div>
</div>


<div class="card">
    <table  id="complaintTables">
        <thead>
            <tr>
                <th>Subject</th>
                <th>Description</th>
                <th>Date</th>
                <th>Status</th>
                <th>Type</th>
                <th>Transformation Direction</th>
                <th>Actions</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-column="subject">@item.subject</td>
                    <td data-column="description">@item.description</td>
                    <td data-column="date">@item.date</td>
                    <td data-column="status">@item.complaintStatus?.status</td>
                    <td data-column="type">@item.complaintType?.Description</td>
                    <td data-column="transformDirection">@item.transformationDirection?.Description</td>
                    <td>
                        <div class="action-buttons">


                            @* <a asp-controller="Complaints" asp-action="Details" asp-route-id="@item.ComplaintId"><i class="fas fa-eye action-btn" title="View"></i></a> *@

                            @*     <a asp-controller="Complaints" asp-action="Edit" asp-route-Id="@item.ComplaintId"><i class="fas fa-edit action-btn" title="Edit"></i></a> *@
                            @*     <a asp-controller="Complaints" asp-action="Delete" asp-route-id="@item.ComplaintId"><i class="fas fa-trash action-btn" title="Delete"></i></a> *@
                            @if (@item.ComplaintStatusId == 1)
                            {
                                <a asp-controller="Complaints" asp-action="Details" asp-route-id="@item.ComplaintId"><i class="fas fa-eye action-btn" title="View"></i></a>

                                @* <a asp-controller="Complaints" asp-action="Edit" asp-route-Id="@item.ComplaintId"><i class="fas fa-edit action-btn" title="Edit"></i></a> *@
                                @* <a asp-controller="Complaints" asp-action="Delete" asp-route-id="@item.ComplaintId"><i class="fas fa-trash action-btn" title="Delete"></i></a> *@
                            }
                            else
                            {
                                <a asp-controller="Complaints" asp-action="Details" asp-route-id="@item.ComplaintId"><i class="fas fa-eye action-btn" title="View"></i></a>

                                <a asp-controller="Deans" asp-action="Edit" asp-route-Id="@item.ComplaintId"><i class="fas fa-edit action-btn" title="Edit"></i></a>
                                <a asp-controller="Deans" asp-action="Delete" asp-route-id="@item.ComplaintId"><i class="fas fa-trash action-btn" title="Delete"></i></a>
                            }

                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>



<script src="~/js/filter.js">

</script>