Controllers/ComplaintStudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CapSystemFinal.Data;
using CapSystemFinal.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
namespace CapSystemFinal.Controllers
{
    [Authorize(Roles = SD.Role_Student)]//Adding this will ensure that no user can access to page if they have the url

    public class ComplaintStudentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ComplaintStudentsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Complaints
        public   IActionResult Index()
        {
            //var user = await _userManager.GetUserAsync(User);
            // var userId = user?.Id;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            List<Complaint> ListObjComplaint = _context.Complaints
    .Include(c => c.complaintStatus)
    .Include(c => c.transformationDirection)
    .Include(c=>c.complaintType)
    .Where(c => String.Equals(c.UserId, userId)).ToList();
            //var userId =  User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Pass to view
            ViewData["UserId"] = userId;
            //var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //ViewData["UserId"] = userId;
             return View((ListObjComplaint));

        }

        //// GET: Complaints/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["ComplaintStatusId"] = _context.ComplaintStatus.Find(id);

        //    var complaint = await _context.Complaints
        //        .Include(c => c.complaintStatus)
        //        .Include(c => c.complaintType)
        //        .Include(c => c.transformationDirection)
        //        .FirstOrDefaultAsync(m => m.ComplaintId == id);
        //    if (complaint == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(complaint);
        //}

        // GET: Complaints/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaint = await _context.Complaints
                .Include(c => c.complaintStatus)
                .Include(c => c.complaintType)
                .Include(c => c.transformationDirection)
                .FirstOrDefaultAsync(m => m.ComplaintId == id);

            if (complaint == null)
            {
                return NotFound();
            }

            // Now just assign the values you want to display:
            ViewData["ComplaintStatus"] = complaint.complaintStatus?.status;
            ViewData["ComplaintType"] = complaint.complaintType?.Description;
            ViewData["TransformationDirection"] = complaint.transformationDirection?.Description;

            return View(complaint);
        }
//🖥 In the View(e.g

        // GET: Complaints/Create
        public IActionResult Create()
        {
            ViewData["ComplaintStatus"] = "Pending";


            ViewData["UserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            ViewData["CurrentDate"] = DateTime.Now.ToString("yyyy-MM-dd");

            // Prepare dropdown lists
            ViewData["CompTypeId"] = new SelectList(_context.ComplaintType, "Id", "Description");
            ViewData["ComplaintStatusId"] = new SelectList(_context.ComplaintStatus, "Id", "status");
            ViewData["TransformationDirectionId"] = new SelectList(_context.TransformationDirection, "Id", "Description");

           


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Complaint complaint)
        {
            
            if (ModelState.IsValid) {

                // 🧠 Logic to get Dean by selected TransformationDirection
                var selectedDirection = await _context.TransformationDirection
                    .FirstOrDefaultAsync(td => td.Id == complaint.TransformationDirectionId);

                if (selectedDirection != null)
                {
                    // Match by description (assuming Dean.Name == Direction.Description)
                    var dean = await _context.Deans
                        .FirstOrDefaultAsync(d => d.Name == selectedDirection.Description);

                    if (dean != null)
                    {
                        complaint.DeanId = dean.DeanId;
                    }
                }

                _context.Add(complaint);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            return View(complaint);
        }



        // GET: Complaints/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var complaint = await _context.Complaints.FindAsync(id);
            if (complaint == null)
            {
                return NotFound();
            }
            //ViewData["CurrentDate"] = new SelectList(_context.Set<Complaint>(), "id", "id", complaint.date);
            ViewData["UserId"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            ViewData["CompTypeId"] = new SelectList(_context.ComplaintType, "Id", "Description");
            ViewData["ComplaintStatusId"] = new SelectList(_context.ComplaintStatus, "Id", "status");
            ViewData["TransformationDirectionId"] = new SelectList(_context.TransformationDirection, "Id", "Description");
           


            return View(complaint);
        }

        // POST: Complaints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(Complaint complaint)
        //{


        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(complaint);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ComplaintExists(complaint.ComplaintId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ComplaintStatusId"] = new SelectList(_context.Set<ComplaintStatus>(), "id", "id", complaint.ComplaintStatusId);
        //    ViewData["CompTypeId"] = new SelectList(_context.Set<ComplaintType>(), "Id", "Id", complaint.CompTypeId);
        //    ViewData["TransformationDirectionId"] = new SelectList(_context.Set<TransformationDirection>(), "Id", "Id", complaint.TransformationDirectionId);
        //    return View(complaint);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Complaint obj)
        {

            var userId = _userManager.GetUserId(User);


            if (ModelState.IsValid)
            {
                // 1. Get the existing complaint from database
                var complaintFromDb = _context.Complaints.Find(id);


                if (complaintFromDb == null)
                {
                    return NotFound();
                }


                //string Oldsubject = complaintFromDb.subject;
                //string Olddescription = complaintFromDb.description;
                //int OldComplaintStatusId = complaintFromDb.ComplaintStatusId;
                //int OldCompTypeId = complaintFromDb.CompTypeId;
                //int OldTransformationDirectionId = complaintFromDb.TransformationDirectionId;
                // 2. Update only the properties that should change
                complaintFromDb.subject = obj.subject;
                complaintFromDb.description = obj.description;
                complaintFromDb.ComplaintStatusId = obj.ComplaintStatusId;
                complaintFromDb.CompTypeId = obj.CompTypeId;
                complaintFromDb.TransformationDirectionId = obj.TransformationDirectionId;





                // 🧠 Logic to get Dean by selected TransformationDirection
                var selectedDirection = await _context.TransformationDirection
                    .FirstOrDefaultAsync(td => td.Id == complaintFromDb.TransformationDirectionId);


                //complaintFromDb.DeanId = _context.Complaints.FirstOrDefault(c => c.DeanId == dean.DeanId);

                //if (selectedDirection != null)
                //{
                //    // Match by description (assuming Dean.Name == Direction.Description)
                //    var dean = await _context.Deans
                //        .FirstOrDefaultAsync(d => d.Name == selectedDirection.Description);

                complaintFromDb.DeanId = selectedDirection.Id;

                //    if (dean != null)
                //    {
                //        complaintFromDb.DeanId = dean.DeanId;
                //    }

                //}



                // 3. Explicitly mark as modified (optional but good practice)

Views/ComplaintStudents/Create.cshtml
@using System.Security.Claims
@model CapSystemFinal.Models.Complaint

@{
    ViewData["Title"] = "Create";
}

<h1>Create Complaint</h1>


<p>@ViewData["studentId"]</p>

<hr />
<div class="row">
  
    <div class="col-md-12">
       
        <form asp-controller="ComplaintStudents" asp-action="Create" method="post">        
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div asp-validation-summary="All"></div>
            @* <input asp-for="ComplaintId" required hidden /> *@
            <div class="form-group mb-2">
                <label asp-for="subject" class="control-label"></label> 
                <input type="text" asp-for="subject" class="form-control" />
                <span asp-validation-for="subject" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="description" class="control-label"></label>
                <input type="text" asp-for="description" class="form-control p-5" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" type="date" value="@ViewData["CurrentDate"]" readonly/>
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group mb-2" hidden>
                <label asp-for="ComplaintStatusId" class="control-label"></label>
                <select asp-for="ComplaintStatusId" class="form-control"  readonly >
                    <option value="2" >@ViewData["ComplaintStatus"]</option>
                </select>
            </div>
            <div class="form-group mb-2">
                <label hidden asp-for="UserId" class="control-label"></label>
                <input type="hidden" name="userId" asp-for="UserId" class="form-control" value="@ViewData["UserId"]" />
            </div>
            
            <div class="form-group mb-2">
                <label asp-for="CompTypeId" class="control-label"></label>
                <select asp-for="CompTypeId" class="form-control" asp-items="ViewBag.CompTypeId"></select>
            </div>
            <div class="form-group mb-2">
                <label asp-for="TransformationDirectionId" class="control-label"></label>
                 <select asp-for="TransformationDirectionId" class ="form-control mb-4" asp-items="ViewBag.TransformationDirectionId">
					<option value="">--Select Transformation Direction --</option>
                 </select>
             </div>
            
            <div class="form-group mb-3 d-flex gap-3">
                @* <input type="submit" value="Create"  class="btn btn-primary" /> *@
                <button type="submit" class="btn btn-primary">
                    @* <i class="fas fa-arrow-left"></i> *@
                    <i class="bi bi-plus-circle"></i>
                    
                    Create
                </button>
                <a asp-action="Index" class="btn btn-outline">
                    <i class="fas fa-arrow-left"></i>
                    Back
                </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ComplaintStudents/Delete.cshtml
@model CapSystemFinal.Models.Complaint

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Complaint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.complaintStatus)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.ComplaintStatusId
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.complaintType)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.CompTypeId
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.transformationDirection)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.TransformationDirectionId
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ComplaintId" />
        <button type="submit" value="Delete" class="btn btn-danger"><i class="bi bi-archive-fill"></i> Delete</button>
        
        

        @* <a asp-action="Index">Back to List</a> *@
        <a asp-action="Index" class="btn btn-outline">
            <i class="fas fa-arrow-left"></i>
            Back
        </a>
    </form>
</div>

Views/ComplaintStudents/Details.cshtml
@model CapSystemFinal.Models.Complaint

@{
    ViewData["Title"] = "Details";
}

<h1>Complaint Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.complaintStatus)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.ComplaintStatus
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.complaintType)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.ComplaintType
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.transformationDirection)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.TransformationDirection
        </dd>
    </dl>
</div>
<div>
    @if (Model?.ComplaintStatusId == 1)
    {
        <div>
            @* <a asp-action="Edit" asp-route-id="@Model?.ComplaintId" type="submit" class="btn btn-primary"> *@
            @*     <i class="bi bi-pencil-square"></i> *@
            @*     Edit *@
            @* </a> *@
            @* <a asp-action="Index">Back to List</a> *@
            <a asp-action="Index" class="btn btn-outline">
                <i class="fas fa-arrow-left"></i>
                Back
            </a>

        </div>
    }

    @if (Model?.ComplaintStatusId != 1)
    {
        
        <div>
            @* <a asp-action="Edit" asp-route-id="@Model?.ComplaintId">Edit</a> *@
            <a asp-action="Edit" asp-route-id="@Model?.ComplaintId" type="submit" class="btn btn-primary">
                <i class="bi bi-pencil-square"></i>
                Edit
            </a>
            @* <a asp-action="Index">Back to List</a> *@
            <a asp-action="Index" class="btn btn-outline">
                <i class="fas fa-arrow-left"></i>
                Back
            </a>
        </div>
    
    }

</div>

Views/ComplaintStudents/Edit.cshtml
@using System.Security.Claims

@model CapSystemFinal.Models.Complaint

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Complaint</h1>


<hr />
<div class="row">   
    <div class="col-md-12">
        <form asp-controller="ComplaintStudents" asp-action="Edit" method="post">

           

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ComplaintId" />
            <div class="form-group mb-3">
                <label asp-for="subject" class="control-label"></label>
                <input asp-for="subject" class="form-control" />
                <span asp-validation-for="subject" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="date" class="control-label"></label>
                <input type="date" asp-for="date" class="form-control" readonly />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="ComplaintStatusId" class="control-label"></label>
                <select asp-for="ComplaintStatusId" class="form-control" asp-items="ViewBag.ComplaintStatusId" disabled>
                    <option asp-for="ComplaintStatusId">--Select Status --</option>

                </select>
               
                <span asp-validation-for="ComplaintStatusId" class="text-danger"></span>
                <!-- Hidden field to preserve the value during form submission -->
                <input type="hidden" asp-for="ComplaintStatusId" />
            </div>

            <div class="form-grou mb-3p">
                <label hidden asp-for="UserId" class="control-label"></label>
                <input type="hidden" name="userId" asp-for="UserId" class="form-control" value="@ViewData["UserId"]" />
            </div>
            <div class="form-group mb-3">
                <label asp-for="CompTypeId" class="control-label"></label>
                <select asp-for="CompTypeId" class="form-control" asp-items="ViewBag.CompTypeId"></select>
                <span asp-validation-for="CompTypeId" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <label asp-for="TransformationDirectionId" class="control-label"></label>
                <select asp-for="TransformationDirectionId" class="form-control" asp-items="ViewBag.TransformationDirectionId"></select>
                <span asp-validation-for="TransformationDirectionId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 d-flex gap-3">
                @* <input type="submit" value="Create"  class="btn btn-primary" /> *@
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-pencil-square"></i>
                    Edit
                </button>
                <a asp-action="Index" class="btn btn-outline">
                    <i class="fas fa-arrow-left"></i>
                    Back
                </a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ComplaintStudents/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<Complaint>
@* @inject UserManager<IdentityUser> UserManager *@
@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/Student/index.css" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />



@* @{ *@
@*     var user = await UserManager.GetUserAsync(User); *@
@*     var userId = user?.Id; *@
@* } *@
@* <p>Your user ID is: @userId</p> *@

@* <p>@ViewData["UserId"]</p> *@


<div class="    d-flex justify-content-between align-items-center">
<h1 class=" m-3 pb-3">Complaints Page</h1>


<p class="m-4">
    <a asp-controller="ComplaintStudents" asp-action="Create" class="btn btn-primary">
        <i class="fas fa-plus"></i>
        New Complaint
    </a>
    @* <a asp-controller="ComplaintStudents" asp-action="Create" asp-route-Id="">Create New</a> *@
</p>
</div>

<hr/>
<div class="d-flex">
    <div class="search-container m-4  w-100 position-relative">

        <input type="text" id="search-input" placeholder="Search Complaints..." class="ps-4 p-2 rounded-2 border-0 w-100" />
        <i class="bi bi-search position-absolute position-adjust text-danger "></i>

    </div>






    <div class="filter-group m-4 w-50 align-content-center">
        <label id="status-filter-label"></label>
        <select id="status-filter" class="w-75 p-2 rounded-2 border-0 ">
            <option value="">Status</option>
            <option value="Pending">Pending</option>
            <option value="In Progress">In Progress</option>
            <option value="Resolved">Resolved</option>
            <option value="Closed">Closed</option>
        </select>



    </div>
</div>

<div class="card">
    <table id="complaintTables">
        <thead>
            <tr>
                <th>Subject</th>
                <th>Description</th>
                <th>Date</th>
                <th>Status</th>
                <th>Type</th>
                <th>Redirect Complaint</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-column="subject">@item.subject</td>
                    <td data-column="description">@item.description</td>
                    <td data-column="date">@item.date</td>

                    <td data-column="status">@item.complaintStatus.status</td>

                    <td data-column="type">@item.complaintType.Description</td>
                    <td data-column="transformDirection">@item.transformationDirection.Description</td>
                    @* @if (item.ComplaintStatusId == 1) *@
                    @* { *@
                    @*            <td data-column="status"><span class="status status-closed">Closed</span></td> *@
                    @* } *@
                    @* <td><span class="status status-open">Open</span></td> *@

                    @* <td><span class="status status-pending">Pending</span></td> *@

                   
                    <td>
                        <div class="action-buttons">
                            @if (@item.ComplaintStatusId == 1)
                            {
                                <a asp-controller="ComplaintStudents" asp-action="Details" asp-route-id="@item.ComplaintId"><i class="fas fa-eye action-btn" title="View"></i></a>

                                @* <a asp-controller="ComplaintStudents" asp-action="Edit" asp-route-Id="@item.ComplaintId"><i class="fas fa-edit action-btn" title="Edit"></i></a> *@
                                @* <a asp-controller="ComplaintStudents" asp-action="Delete" asp-route-id="@item.ComplaintId"><i class="fas fa-trash action-btn" title="Delete"></i></a> *@

                            }
                            else
                            {
                                <a asp-controller="ComplaintStudents" asp-action="Details" asp-route-id="@item.ComplaintId"><i class="fas fa-eye action-btn" title="View"></i></a>

                                <a asp-controller="ComplaintStudents" asp-action="Edit" asp-route-Id="@item.ComplaintId"><i class="fas fa-edit action-btn" title="Edit"></i></a>
                                <a asp-controller="ComplaintStudents" asp-action="Delete" asp-route-id="@item.ComplaintId"><i class="fas fa-trash action-btn" title="Delete"></i></a>

                            }

                            @* <a asp-controller="ComplaintStudents" asp-action="Details" asp-route-id="@item.ComplaintId"><i class="fas fa-eye action-btn" title="View"></i></a> *@

                            @* <a asp-controller="ComplaintStudents" asp-action="Edit" asp-route-Id="@item.ComplaintId"><i class="fas fa-edit action-btn" title="Edit"></i></a> *@
                            @* <a asp-controller="ComplaintStudents" asp-action="Delete" asp-route-id="@item.ComplaintId" ><i class="fas fa-trash action-btn" title="Delete"></i></a> *@

                            
                        </div>
                    </td>
                </tr>
                 }
            
            </tbody>
          
            </table>
        
</div>




<script src="~/js/filter.js">
  
</script>